version: '3.7'

networks:
  public_network:
  global_db_network:
    external: true # Declares global_db_network as an existing network

volumes:
  dapp_mentors_data:

services:
  fullstack:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend_service
    restart: unless-stopped
    ports:
      - '3005:3000'
    volumes:
      - dapp_mentors_data:/data
    networks:
      - public_network
      - global_db_network # Direct MongoDB access
    env_file:
      - .env
